# -*- coding: utf-8 -*-
"""practical-01 AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkRtmee5t7sOTg7AqFwiV6GwzU5SnNU3
"""

print("Hello! I am Python.")
print("Today we will build a cleaning robot together. 🤖")
print(2 + 3, "is the answer to 2 + 3")

# This is our room: 5 spots. D = dirty, C = clean
room = ["D", "C", "D", "D", "C"]

# A helper that draws the room with nice symbols
def show_room(room):
    picture = ""
    for spot in room:
        if spot == "D":
            picture += "💩 "
        else:
            picture += "✨ "
    print(picture)

print("Our room right now:")
show_room(room)

# The robot looks at ONE spot and decides what to do.
def clean_spot(spot):
    if spot == "D":
        return "C"
    else:
        return "C"

# Let's test the robot on one dirty spot:
result = clean_spot("D")
print("The robot looked at a dirty spot 💩 and made it:", result,
      "(C means clean ✨)")

print("BEFORE - the dirty room:")
show_room(room)

# The robot visits every spot, one by one
for i in range(len(room)):
    room[i] = clean_spot(room[i])
    print("After cleaning spot number", i + 1, ":")
    show_room(room)

print()
print("AFTER - all done! ✨🤖")

"""BASIC CHAT BOARD USING PYTHON

"""

# Basic Chatbot in Python

print("🤖 ChatBot: Hello! I am your chatbot.")
print("Type 'bye' to exit.\n")

while True:
    user = input("You: ").lower()

    if user == "hello" or user == "hi":
        print("ChatBot: Hello! How are you?")

    elif "how are you" in user:
        print("ChatBot: I am fine. Thanks for asking!")

    elif "your name" in user:
        print("ChatBot: My name is Python ChatBot.")

    elif "time" in user:
        from datetime import datetime
        current_time = datetime.now().strftime("%H:%M:%S")
        print("ChatBot: Current time is", current_time)

    elif "thank" in user:
        print("ChatBot: You're welcome!")

    elif user == "bye":
        print("ChatBot: Goodbye! Have a nice day.")
        break

    else:
        print("ChatBot: Sorry, I don't understand that.")

